backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "events"
    label: "Events"
    format: "json"
    extension: "json"
    create: true
    identifier_field: "id"
    files:
      - file: "assets/events.json"
        label: "Events"
        name: "events"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Location / Where", name: "where", widget: "string", required: false }
          - { label: "Start (for one-time events)", name: "start", widget: "datetime", required: false }
          - { label: "Recurrence Rule", name: "rrule", widget: "string", required: false, hint: "Use RRULE, e.g. FREQ=WEEKLY;BYDAY=SU;BYHOUR=10;BYMINUTE=0" }
          - { label: "Duration (minutes)", name: "duration_minutes", widget: "number", default: 60 }
          - { label: "Type", name: "type", widget: "select", options: ["svc", "aa", "na", "holy", "other"], default: "other" }
